// Generated by https://pagedraw.io/pages/13358
import React from 'react';
import './_agy.css';


export default class _agy extends React.Component {
  render() {
    return (
      <div className="_agy-_agy-0">
          <div className="_agy-0">
              <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/4dfa/9195/58bacfa09df1e6057f73fe44b5a8f552" className="_agy-image-2" /> 
          </div>
      </div>
    );
  }
};
