// Generated by https://pagedraw.io/pages/13358
import React from 'react';
import './component_2.css';


export default class Component_2 extends React.Component {
  render() {
    return (
      <div className="component_2-component_2">
          <div className="component_2-0">
              <div className="component_2-rectangle_2_">
                  <div className="component_2-0-0-0">
                      <div className="component_2-rectangle_2">
                          <div className="component_2-0-0-0-0-0">
                              <div className="component_2-menu-item_-0">
                                  {"Menu-Item №"}
                              </div>
                          </div>
                      </div>
                  </div>
                  <div className="component_2-0-0-1">
                      <div className="component_2-rectangle_2-0">
                          <div className="component_2-0-0-1-0-0">
                              <div className="component_2-menu-item_-00">
                                  {"Menu-Item №"}
                              </div>
                          </div>
                      </div>
                  </div>
                  <div className="component_2-0-0-2">
                      <div className="component_2-rectangle_2-00">
                          <div className="component_2-0-0-2-0-0">
                              <div className="component_2-menu-item_-000">
                                  {"Menu-Item №"}
                              </div>
                          </div>
                      </div>
                  </div>
                  <div className="component_2-0-0-3">
                      <div className="component_2-0-0-3-0">
                          <div className="component_2-0-0-3-0-0">
                              <div className="component_2-0-0-3-0-0-0">
                                  <div className="component_2-menu-item_-0000">
                                      {"Menu-Item №"}
                                  </div>
                                  <div className="component_2-rectangle_2-000" /> 
                              </div>
                          </div>
                      </div>
                  </div>
                  <div className="component_2-0-0-4">
                      <div className="component_2-rectangle_2-0000">
                          <div className="component_2-0-0-4-0-0">
                              <div className="component_2-menu-item_-00000">
                                  {"Menu-Item №"}
                              </div>
                          </div>
                      </div>
                  </div>
                  <div className="component_2-0-0-5">
                      <div className="component_2-rectangle_2-00000">
                          <div className="component_2-0-0-5-0-0">
                              <div className="component_2-menu-item_-000002">
                                  {"Menu-Item №"}
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
