// Generated by https://pagedraw.io/pages/13358
import React from 'react';
import Component_2 from './component_2';
import './container.css';


export default class Container extends React.Component {
  render() {
    return (
      <div className="container-container-0">
          <div className="container-0">
              <div className="container-0-0">
                  <div className="container-0-0-0">
                      <div className="container-0-0-0-0">
                          <div className="container-first-page1">
                              <div className="container-0-0-0-0-0-0">
                                  <div className="container-image-1">
                                      <div className="container-0-0-0-0-0-0-0-0">
                                          <div className="container-rectangle_2_">
                                              <div className="container-0-0-0-0-0-0-0-0-0-0">
                                                  <div className="container-0-0-0-0-0-0-0-0-0-0-0">
                                                      <div className="container-0-0-0-0-0-0-0-0-0-0-0-0">
                                                          <div className="container-0-0-0-0-0-0-0-0-0-0-0-0-0">
                                                              <div className="container-component_2">
                                                                  <Component_2 /> 
                                                              </div>
                                                              <div className="container-menu-item_-0">
                                                                  {"Menu-Item №"}
                                                              </div>
                                                              <div className="container-rectangle_2">
                                                                  <div className="container-0-0-0-0-0-0-0-0-0-0-0-0-0-2-0">
                                                                      <div className="container-menu-item_-00">
                                                                          {"Menu-Item №"}
                                                                      </div>
                                                                  </div>
                                                              </div>
                                                              <div className="container-rectangle_2-0">
                                                                  <div className="container-0-0-0-0-0-0-0-0-0-0-0-0-0-3-0">
                                                                      <div className="container-menu-item_-000">
                                                                          {"Menu-Item №"}
                                                                      </div>
                                                                  </div>
                                                              </div>
                                                              <div className="container-rectangle_2-00">
                                                                  <div className="container-0-0-0-0-0-0-0-0-0-0-0-0-0-4-0">
                                                                      <div className="container-menu-item_-0000">
                                                                          {"Menu-Item №"}
                                                                      </div>
                                                                  </div>
                                                              </div>
                                                              <div className="container-menu-item_-00000">
                                                                  {"Menu-Item №"}
                                                              </div>
                                                              <div className="container-rectangle_2-000">
                                                                  <div className="container-0-0-0-0-0-0-0-0-0-0-0-0-0-6-0">
                                                                      <div className="container-menu-item_-000001">
                                                                          {"Menu-Item №"}
                                                                      </div>
                                                                  </div>
                                                              </div>
                                                              <div className="container-rectangle_2-0000" /> 
                                                              <div className="container-rectangle_2-00000" /> 
                                                              <div className="container-menu-item_-0000011">
                                                                  {"Menu-Item №"}
                                                              </div>
                                                              <div className="container-rectangle_2-000000" /> 
                                                          </div>
                                                      </div>
                                                  </div>
                                              </div>
                                              <div className="container-0-0-0-0-0-0-0-0-0-1">
                                                  <div className="container-rectangle_2-0000006">
                                                      <div className="container-0-0-0-0-0-0-0-0-0-1-0-0">
                                                          <div className="container-menu-item_-000000">
                                                              {"Menu-Item №"}
                                                          </div>
                                                      </div>
                                                  </div>
                                              </div>
                                              <div className="container-0-0-0-0-0-0-0-0-0-2">
                                                  <div className="container-0-0-0-0-0-0-0-0-0-2-0">
                                                      <div className="container-0-0-0-0-0-0-0-0-0-2-0-0">
                                                          <div className="container-0-0-0-0-0-0-0-0-0-2-0-0-0">
                                                              <div className="container-menu-item_-000003">
                                                                  {"Menu-Item №"}
                                                              </div>
                                                              <div className="container-rectangle_2-000002" /> 
                                                          </div>
                                                      </div>
                                                  </div>
                                              </div>
                                              <div className="container-0-0-0-0-0-0-0-0-0-3">
                                                  <div className="container-0-0-0-0-0-0-0-0-0-3-0">
                                                      <div className="container-0-0-0-0-0-0-0-0-0-3-0-0">
                                                          <div className="container-0-0-0-0-0-0-0-0-0-3-0-0-0">
                                                              <div className="container-menu-item_-00000117">
                                                                  {"Menu-Item №"}
                                                              </div>
                                                              <div className="container-rectangle_2-0000003" /> 
                                                          </div>
                                                      </div>
                                                  </div>
                                              </div>
                                          </div>
                                          <div className="container-0-0-0-0-0-0-0-0-1">
                                              <div className="container-0-0-0-0-0-0-0-0-1-0">
                                                  <div className="container-0-0-0-0-0-0-0-0-1-0-0">
                                                      <div className="container-b-8">
                                                          Source component not found
                                                      </div>
                                                      <div className="container-_-0">
                                                          {"КРУГОБАЙКАЛЬСКАЯ ЖЕЛЕЗНАЯ ДОРОГА "}
                                                      </div>
                                                      <div className="container-arrow-0" /> 
                                                      <div className="container-arrow-00" /> 
                                                  </div>
                                              </div>
                                          </div>
                                      </div>
                                  </div>
                              </div>
                          </div>
                          <div className="container-first-page-0">
                              <div className="container-0-0-0-0-1-0">
                                  <div className="container-image-5">
                                      <div className="container-0-0-0-0-1-0-0-0">
                                          <div className="container-rectangle_3">
                                              <div className="container-0-0-0-0-1-0-0-0-0-0">
                                                  <div className="container-rectangle-0" /> 
                                              </div>
                                              <div className="container-0-0-0-0-1-0-0-0-0-1">
                                                  <div className="container-rectangle-00" /> 
                                              </div>
                                              <div className="container-0-0-0-0-1-0-0-0-0-2">
                                                  <div className="container-rectangle-000" /> 
                                              </div>
                                          </div>
                                      </div>
                                      <div className="container-0-0-0-0-1-0-0-1">
                                          <div className="container-component-0">
                                              <div className="container-0-0-0-0-1-0-0-1-0-0">
                                                  <div className="container-_-00">
                                                      {"КРУГОБАЙКАЛЬСКАЯ ЖЕЛЕЗНАЯ ДОРОГА "}
                                                  </div>
                                              </div>
                                          </div>
                                      </div>
                                  </div>
                              </div>
                          </div>
                          <div className="container-rectangle_2-000001" /> 
                          <div className="container-arrow-000" /> 
                          <div className="container-arrow-0000" /> 
                      </div>
                  </div>
              </div>
          </div>
          <div className="container-1">
              <div className="container-rectangle-0000" /> 
          </div>
          <div className="container-2">
              <div className="container-rectangle-00000" /> 
          </div>
          <div className="container-3">
              <div className="container-rectangle-000001" /> 
          </div>
          <div className="container-4">
              <div className="container-rectangle-000003" /> 
          </div>
          <div className="container-5">
              <div className="container-rectangle-0000034" /> 
          </div>
          <div className="container-6">
              <div className="container-page6">
                  <div className="container-6-0-0">
                      <div className="container-6-0-0-0">
                          <div className="container-6-0-0-0-0">
                              <div className="container-rectangle-0000011" /> 
                          </div>
                          <div className="container-6-0-0-0-1">
                              <div className="container-rectangle-000000" /> 
                          </div>
                          <div className="container-6-0-0-0-2">
                              <div className="container-rectangle-0000038" /> 
                          </div>
                      </div>
                      <div className="container-_-000">
                          {"КБЖД в наше время"}
                      </div>
                  </div>
                  <div className="container-6-0-1">
                      <div className="container-_-_8">
                          <div>{"Современная кругобайкалка является историко-архитектурным памятником и используется в основном, туристами. Это 89 километров байкальской красоты, которые можно проехать на старинном поезде, сквозь арки и тоннели, спроектированные итальянскими мастерами. Вы увидите Байкал с высоты и остановитесь в самых красивых местах. Плюс – 171 км от станции Слюдянка-2 до Мысовой, проложенные вдоль южной части тектонической трещины озера Байкал. С другой стороны от железной дороги дороги располагается Олхинское плато. Это – возвышенность практически треугольной формы, ограниченная Тункинскими Гольцами, Приморским хребтом, речкой Иркут и Иркутским водохранилищем. С точки зрения туристической привлекательности Олхинское"}</div>
                          <div>{" плато является крайне живописным объектом. Это – поросшая лесами средневысокая возвышенность, усеянная скалами останцами. Многие из них имеют оригинальный «дизайн» и личные имена. Например – Идол, Старуха Изергиль, Витязь или Зеркала. Максимальная точка возвышенности – Камень Мойготы, Активно использовалась в ритуальных действах коренного народа – тунгусов."}</div>
                      </div>
                  </div>
              </div>
          </div>
          <div className="container-7">
              <div className="container-frame_4">
                  <div className="container-7-0-0">
                      <div className="container-image-9">
                          <div className="container-7-0-0-0-0">
                              <div className="container-rectangle-0000001" /> 
                          </div>
                          <div className="container-7-0-0-0-1">
                              <div className="container-rectangle-0000010" /> 
                          </div>
                          <div className="container-7-0-0-0-2">
                              <div className="container-rectangle-0000015" /> 
                          </div>
                      </div>
                  </div>
              </div>
          </div>
          <div className="container-8">
              <div className="container-8-0">
                  <div className="container-8-0-0">
                      <div className="container-8-0-0-0">
                          <div className="container-footer-0">
                              <div className="container-8-0-0-0-0-0">
                                  <div className="container-8-0-0-0-0-0-0">
                                      <div className="container-image-51">
                                          <div className="container-8-0-0-0-0-0-0-0-0">
                                              <div className="container-rectangle-0000032" /> 
                                          </div>
                                          <div className="container-8-0-0-0-0-0-0-0-1">
                                              <div className="container-rectangle-0000013" /> 
                                          </div>
                                          <div className="container-8-0-0-0-0-0-0-0-2">
                                              <div className="container-rectangle-000002" /> 
                                          </div>
                                      </div>
                                      <div className="container-rectangle-0000003">
                                          <div className="container-8-0-0-0-0-0-0-1-0">
                                              <div className="container-rectangle_4-0">
                                                  <div className="container-8-0-0-0-0-0-0-1-0-0-0">
                                                      <div className="container-rectangle_4" /> 
                                                  </div>
                                              </div>
                                          </div>
                                      </div>
                                      <div className="container-drill_team-0">DRILL TEAM</div>
                                      <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/0aa9/23c7/84b7ba9ca8f1f14fbf846c4eb203156b" className="container-image-2" /> 
                                      <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/0a05/66b7/f6309900ab32fcb496e34379a4cb577c" className="container-image-18" /> 
                                      <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/d020/49e4/a8a6bf8434bf2ca4cbb09082b6a124d6" className="container-image-11" /> 
                                      <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/2d61/dd37/b61eac2e2f3ad3b3a4c94db025a01b14" className="container-image-0" /> 
                                  </div>
                              </div>
                          </div>
                          <div className="container-rectangle_3-0">
                              <div className="container-8-0-0-0-1-0">
                                  <div className="container-made_rect_by_react-0">
                                      MADE RECT BY REACT
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
