// Generated by https://pagedraw.io/pages/13358
import React from 'react';
import './ellipse.css';


export default class Ellipse extends React.Component {
  render() {
    return (
      <div className="ellipse-ellipse-00">
          <div className="ellipse-0">
              <div className="ellipse-ellipse-0" /> 
          </div>
      </div>
    );
  }
};
