// Generated by https://pagedraw.io/pages/13358
import React from 'react';
import './frame_3.css';


export default class Frame_3 extends React.Component {
  render() {
    return (
      <div className="frame_3-frame_3">
          <div className="frame_3-0">
              <div className="frame_3-r_u_gay_-0">{"R U GAY ? !"}</div>
          </div>
      </div>
    );
  }
};
