// Generated by https://pagedraw.io/pages/13358
import React from 'react';
import './page5.css';


export default class Page5 extends React.Component {
  render() {
    return (
      <div className="page5-page5">
          <div className="page5-0">
              <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/8e6e/9337/6e465b0680df11ce05e0bb44c417a80e" className="page5-image-9" /> 
              <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/f5e2/d241/d195ae880ea946d90ee85275c3cb13b8" className="page5-image-3" /> 
          </div>
          <div className="page5-1">
              <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/f1ba/d45a/ac3c7202981eb89b7cfb852ae6f96bd6" className="page5-image-0" /> 
          </div>
      </div>
    );
  }
};
