// Generated by https://pagedraw.io/pages/13358
import React from 'react';
import './page3.css';


export default class Page3 extends React.Component {
  render() {
    return (
      <div className="page3-page3">
          <div className="page3-0">
              <div className="page3-rectangle-0" /> 
          </div>
          <div className="page3-1">
              <div className="page3-rectangle-00" /> 
          </div>
      </div>
    );
  }
};
