// Generated by https://pagedraw.io/pages/13358
import React from 'react';
import './second-page.css';


export default class Second_page extends React.Component {
  render() {
    return (
      <div className="second-page-second-page-0">
          <div className="second-page-0">
              <div className="second-page-rectangle-0" /> 
          </div>
          <div className="second-page-1">
              <div className="second-page-_-0">
                  {"Кругобайкальская железная дорога"}
              </div>
          </div>
          <div className="second-page-2">
              <div className="second-page-_-_-_-0">
                  {"Кругобайкальскую железную дорогу можно по праву назвать главной достопримечательностью на Байкале. Аналогов Кругобайкалке нет в мире. Это уникальный комплексный музей. Причем дорога и территория, прилегающая к ней, включают в себя не только многочисленные памятники инженерно-технического искусства и архитектуры, но и разнообразные памятники природы - геологии, минералогии, зоологии, биологии."}
              </div>
          </div>
      </div>
    );
  }
};
