// Generated by https://pagedraw.io/pages/13358
import React from 'react';
import './workspace.css';


export default class Workspace extends React.Component {
  render() {
    return (
      <div className="workspace-workspace-0">
          <div className="workspace-0">
              <div className="workspace-0-0">
                  <div className="workspace-0-0-0">
                      <div className="workspace-0-0-0-0">
                          <div className="workspace-b-4">
                              Source component not found
                          </div>
                          <div className="workspace-rectangle-000">
                              <div className="workspace-0-0-0-0-1-0">
                                  <div className="workspace-play_button-0" /> 
                                  <div className="workspace-rectangle-0" /> 
                                  <div className="workspace-rectangle-00" /> 
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
          <div className="workspace-1">
              <div className="workspace-1-0">
                  <div className="workspace-1-0-0">
                      <div className="workspace-play_button-000">
                          <div className="workspace-1-0-0-0-0">
                              <div className="workspace-play_button-00" /> 
                          </div>
                      </div>
                  </div>
              </div>
              <div className="workspace-1-1">
                  <div className="workspace-1-1-0">
                      <div className="workspace-rectangle-0000" /> 
                  </div>
              </div>
              <div className="workspace-1-2">
                  <div className="workspace-1-2-0">
                      <div className="workspace-rectangle-00000" /> 
                  </div>
              </div>
              <div className="workspace-1-3">
                  <div className="workspace-1-3-0">
                      <div className="workspace-1-3-0-0">
                          <div className="workspace-rectangle_2" /> 
                          <div className="workspace-menu-item_-0">
                              {"Menu-Item №"}
                          </div>
                      </div>
                  </div>
              </div>
              <div className="workspace-1-4">
                  <div className="workspace-1-4-0">
                      <div className="workspace-1-4-0-0">
                          <div className="workspace-menu-item_-00">
                              {"Menu-Item №"}
                          </div>
                          <div className="workspace-rectangle_2-0" /> 
                      </div>
                  </div>
              </div>
          </div>
          <div className="workspace-2">
              <div className="workspace-2-0">
                  <div className="workspace-2-0-0">
                      <div className="workspace-nav-0">
                          <div className="workspace-2-0-0-0-0">
                              <div className="workspace-rectangle-0000017">
                                  <div className="workspace-2-0-0-0-0-0-0">
                                      <div className="workspace-2-0-0-0-0-0-0-0">
                                          <div className="workspace-2-0-0-0-0-0-0-0-0">
                                              <div className="workspace-2-0-0-0-0-0-0-0-0-0">
                                                  <div className="workspace-b-6">
                                                      Source component not found
                                                  </div>
                                                  <div className="workspace-play_button-0000" /> 
                                              </div>
                                          </div>
                                      </div>
                                      <div className="workspace-rectangle-000000" /> 
                                      <div className="workspace-rectangle-000001" /> 
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
                  <div className="workspace-2-0-1">
                      <div className="workspace-rectangle-000003" /> 
                  </div>
              </div>
              <div className="workspace-2-1">
                  <div className="workspace-2-1-0">
                      <div className="workspace-component-0">
                          <div className="workspace-2-1-0-0-0">
                              <div className="workspace-right-menu-0">
                                  <div className="workspace-2-1-0-0-0-0-0">
                                      <div className="workspace-2-1-0-0-0-0-0-0">
                                          <div className="workspace-2-1-0-0-0-0-0-0-0">
                                              <div className="workspace-2-1-0-0-0-0-0-0-0-0">
                                                  <div className="workspace-menu-item_-000">
                                                      {"Menu-Item №"}
                                                  </div>
                                                  <div className="workspace-rectangle_2-00" /> 
                                                  <div className="workspace-menu-item_-0000">
                                                      {"Menu-Item №"}
                                                  </div>
                                                  <div className="workspace-rectangle_2-000" /> 
                                              </div>
                                          </div>
                                      </div>
                                  </div>
                                  <div className="workspace-2-1-0-0-0-0-1">
                                      <div className="workspace-2-1-0-0-0-0-1-0">
                                          <div className="workspace-2-1-0-0-0-0-1-0-0">
                                              <div className="workspace-2-1-0-0-0-0-1-0-0-0">
                                                  <div className="workspace-menu-item_-00000">
                                                      {"Menu-Item №"}
                                                  </div>
                                                  <div className="workspace-rectangle_2-0000" /> 
                                              </div>
                                          </div>
                                      </div>
                                  </div>
                                  <div className="workspace-2-1-0-0-0-0-2">
                                      <div className="workspace-rectangle_2-00000">
                                          <div className="workspace-2-1-0-0-0-0-2-0-0">
                                              <div className="workspace-menu-item_-000000">
                                                  {"Menu-Item №"}
                                              </div>
                                          </div>
                                      </div>
                                  </div>
                                  <div className="workspace-2-1-0-0-0-0-3">
                                      <div className="workspace-rectangle_2-000003">
                                          <div className="workspace-2-1-0-0-0-0-3-0-0">
                                              <div className="workspace-menu-item_-0000000">
                                                  {"Menu-Item №"}
                                              </div>
                                          </div>
                                      </div>
                                  </div>
                                  <div className="workspace-2-1-0-0-0-0-4">
                                      <div className="workspace-rectangle_2-000002">
                                          <div className="workspace-2-1-0-0-0-0-4-0-0">
                                              <div className="workspace-menu-item_-000001">
                                                  {"Menu-Item №"}
                                              </div>
                                          </div>
                                      </div>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              <div className="workspace-2-2">
                  <div className="workspace-2-2-0">
                      <div className="workspace-right-menu-00">
                          <div className="workspace-2-2-0-0-0">
                              <div className="workspace-2-2-0-0-0-0">
                                  <div className="workspace-2-2-0-0-0-0-0">
                                      <div className="workspace-2-2-0-0-0-0-0-0">
                                          <div className="workspace-menu-item_-0000006">
                                              {"Menu-Item №"}
                                          </div>
                                          <div className="workspace-rectangle_2-000000" /> 
                                      </div>
                                  </div>
                              </div>
                          </div>
                          <div className="workspace-2-2-0-0-1">
                              <div className="workspace-2-2-0-0-1-0">
                                  <div className="workspace-2-2-0-0-1-0-0">
                                      <div className="workspace-2-2-0-0-1-0-0-0">
                                          <div className="workspace-menu-item_-000002">
                                              {"Menu-Item №"}
                                          </div>
                                          <div className="workspace-rectangle_2-0000006" /> 
                                      </div>
                                  </div>
                              </div>
                          </div>
                          <div className="workspace-2-2-0-0-2">
                              <div className="workspace-2-2-0-0-2-0">
                                  <div className="workspace-2-2-0-0-2-0-0">
                                      <div className="workspace-2-2-0-0-2-0-0-0">
                                          <div className="workspace-menu-item_-000003">
                                              {"Menu-Item №"}
                                          </div>
                                          <div className="workspace-rectangle_2-000001" /> 
                                      </div>
                                  </div>
                              </div>
                          </div>
                          <div className="workspace-2-2-0-0-3">
                              <div className="workspace-rectangle_2-0000039">
                                  <div className="workspace-2-2-0-0-3-0-0">
                                      <div className="workspace-menu-item_-0000005">
                                          {"Menu-Item №"}
                                      </div>
                                  </div>
                              </div>
                          </div>
                          <div className="workspace-2-2-0-0-4">
                              <div className="workspace-rectangle_2-000004">
                                  <div className="workspace-2-2-0-0-4-0-0">
                                      <div className="workspace-menu-item_-0000011">
                                          {"Menu-Item №"}
                                      </div>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
